//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPDV
    {
        public string MAPDV { get; set; }
        public string MADV { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<int> SLDV { get; set; }
    
        public virtual PHIEUDICHVU PHIEUDICHVU { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
