//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public int ID { get; set; }
        public string MANV { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<int> IDPHANQUYEN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
