//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public string MANV { get; set; }
        public string MAPDP { get; set; }
        public Nullable<System.DateTime> NGLAPHD { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string MADT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUDATPHONG PHIEUDATPHONG { get; set; }
    }
}
