//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Model
{
    using QLKhachSan.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPHONG : BasicViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIPHONG()
        {
            this.PHONGs = new HashSet<PHONG>();
        }

        private string _MALOAI;
        public string MALOAI { get { return _MALOAI; } set { _MALOAI = value; OnPropertyChanged(); } }
        private int? _SLGIUONG;
        public int? SLGIUONG { get { return _SLGIUONG; } set { _SLGIUONG = value; OnPropertyChanged(); } }
        private int? _NGUOITOIDA;
        public int? NGUOITOIDA { get { return _NGUOITOIDA; } set { _NGUOITOIDA = value; OnPropertyChanged(); } }
        private double? _DIENTICH;
        public double? DIENTICH { get { return _DIENTICH; } set { _DIENTICH = value; OnPropertyChanged(); } }
        private string _LOAIGIUONG;
        public string LOAIGIUONG { get { return _LOAIGIUONG; } set { _LOAIGIUONG = value; OnPropertyChanged(); } }
        private decimal? _GIA;
        public decimal? GIA { get { return _GIA; } set { _GIA = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
